import numpy as np

In [24]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [25]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [26]:
# get dimersion
a.ndim
b.ndim

2

In [27]:
#get shape
a.shape
b.shape

(2, 3)

In [28]:
# get type 
a.dtype

dtype('int32')

In [29]:
#get size
# if float 8 will appear
b.itemsize

4

In [30]:
#get totoal size
b.size

6

In [31]:
# size * itemsize
a.nbytes

12

accesing/changun soecufuc elements, rows,columns etc

In [32]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
# get specific element
a[1,5]

13

In [35]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# get a specific column
a[:,0]

array([1, 8])

In [37]:
# geting little fancy [startindex,endindex,stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [39]:
a[0,1:-1:2]

array([2, 4, 6])

In [41]:
a[1,5] = 20

In [44]:
print(a)

a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3-d example

In [47]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# get specific elemtnt here
b[:,:,0]

array([[1, 3],
       [5, 7]])

In [55]:
b[:,1,:] = [[9,9],[8,8]]

In [56]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


initialzing different types of arrays

In [63]:
# all o's matrix
np.zeros((2,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [65]:
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [67]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [68]:
# any other number (full like)
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [70]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [71]:
np.full(a.shape,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [72]:
# RAndom devimal numbers 
np.random.rand(4,2)

array([[0.72834986, 0.05802306],
       [0.15971802, 0.40145538],
       [0.61329622, 0.44827305],
       [0.63248637, 0.29550463]])

In [81]:
# random integers values
np.random.randint(-4,7,size= (3,3))

array([[ 4,  0,  0],
       [-4, -4,  4],
       [ 1, -4,  1]])

In [84]:
#idenety
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [98]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))

output[0:-2,0:-2] = z
print(z)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### be carefull when copying array

In [103]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### mathematics

In [104]:
a = np.array([1,2,3,4])

In [105]:
a + 2

array([3, 4, 5, 6])

In [106]:
a -2

array([-1,  0,  1,  2])

In [107]:
a * 2

array([2, 4, 6, 8])

In [108]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [109]:
a+2

array([3, 4, 5, 6])

In [110]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [111]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [112]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# linear algebra

In [117]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [119]:
c = np.identity(3)
np.linalg.det(c)

1.0

# statistics

In [121]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.max(stats,axis=1)

array([3, 6])

In [129]:
np.sum(stats,axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [137]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [140]:
# vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
# horizontal stack
# vertical stack
v1 = np.ones((2,4))
v2 = np.ones((2,2))
print(v1)
print(v2)

np.hstack((v1,v2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]]


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# misclannesous
### load data from file